spring.application.name=task-scheduler
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# This url should go in the H2 console
# Spring app -> connects to DB A
# H2 console -> trying to connect to DB B
spring.datasource.url=jdbc:h2:file:./data/testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
